name: CI builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read


jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04]
        compiler: [g++-12, g++-13, g++-12, g++-14, clang++-16, clang++-17, clang++-18]
        arch: [x64, arm64]

    env:
      CPM_SOURCE_CACHE: "${{ github.workspace }}/.cpm-cache"

    steps:
      - uses: actions/checkout@v6

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.21
        with:
          key: ${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.arch }}

      - name: Using the GitHub Cache Action for CPM sources
        id: cache-cpm
        uses: actions/cache@v5
        env:
          cache-name: cache-cpm-modules
        with:
          path: ${{ env.CPM_SOURCE_CACHE }}
          key: ${{ runner.os }}-builder-${{ env.cache-name }}-${{ matrix.compiler }}-${{ matrix.arch }}
          restore-keys: |
            ${{ runner.os }}-builder-${{ env.cache-name }}-
            ${{ runner.os }}-builder-

      - name: Create CPM cache dir
        run: mkdir -p ${{ env.CPM_SOURCE_CACHE }}

      - name: Configure, Build, and Test Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          run-test: true
          options: CMAKE_BUILD_TYPE=Release CMAKE_CXX_COMPILER_LAUNCHER=ccache CMAKE_CXX_COMPILER=${{ matrix.compiler }}

  build-macos:
    needs: build-windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-15, macos-15, macos-26]

    env:
      CPM_SOURCE_CACHE: "${{ github.workspace }}/.cpm-cache"

    steps:
      - uses: actions/checkout@v6

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.21
        with:
          key: ${{ matrix.os }}-${{ matrix.compiler }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.compiler }}

      - name: Create CPM cache dir
        run: mkdir -p ${{ env.CPM_SOURCE_CACHE }}

      - name: Configure, Build, and Test Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          run-test: true
          options: CMAKE_BUILD_TYPE=Release CMAKE_CXX_COMPILER_LAUNCHER=ccache

  build-windows:
    needs: build-linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - { os: windows-2025-vs2026, arch: x64, toolset: "14.50", build_type: Release } # msvc 2026
          - { os: windows-2025,        arch: x64, toolset: "14.44", build_type: Release } # msvc 2022

    env:
      CPM_SOURCE_CACHE: "${{ github.workspace }}/.cpm-cache"

    steps:
      - uses: actions/checkout@v6

      - name: Cache CPM sources
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/cpm-cache
          key: cpm-${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: cpm-${{ runner.os }}-${{ matrix.arch }}-

      - name: Set up sccache
        uses: hendrikmuhs/ccache-action@v1.2.21
        with:
          key: windows-${{ matrix.arch }}-${{ matrix.build_type }}
          variant: sccache

      - name: Set up MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: ${{ matrix.arch }}
          toolset: ${{ matrix.toolset }}

      - name: Configure, build, and test
        env:
          CPM_SOURCE_CACHE: ${{ runner.temp }}/cpm-cache
        run: |
          cmake -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake --build build --parallel
          ctest --test-dir build --output-on-failure
